// Morse Code Trainer - Data File
// Contains all morse code mappings, words, and sentences

const MORSE_DATA = {
    // Morse code for letters
    morseCode: {
        'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.',
        'G': '--.', 'H': '....', 'I': '..', 'J': '.---', 'K': '-.-', 'L': '.-..',
        'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 'Q': '--.-', 'R': '.-.',
        'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-',
        'Y': '-.--', 'Z': '--..'
    },
    
    // Morse code for numbers
    morseNumbers: {
        '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-',
        '5': '.....', '6': '-....', '7': '--...', '8': '---..', '9': '----.'
    },
    
    // Words organized by difficulty level
    wordsByLevel: {
        easy: [
            'HELLO', 'WORLD', 'MORSE', 'CODE', 'DOT', 'DASH', 'SOS', 'HELP',
            'SAVE', 'LIFE', 'STOP', 'GO', 'YES', 'NO', 'OKAY', 'FINE', 'GOOD',
            'BAD', 'UP', 'DOWN', 'LEFT', 'RIGHT', 'FIRE', 'WATER', 'EARTH',
            'AIR', 'SUN', 'MOON', 'STAR', 'SKY', 'SEA', 'LAND', 'TREE', 'BIRD',
            'FISH', 'DOG', 'CAT', 'HORSE', 'COW', 'SHEEP', 'BOOK', 'PEN', 'MAP',
            'KEY', 'DOOR', 'WIND', 'RAIN', 'SNOW', 'HOT', 'COLD', 'WARM', 'COOL',
            'HELLO', 'WORLD', 'MORSE', 'CODE', 'DOT', 'DASH', 'SOS', 'HELP',
            'SAVE', 'LIFE', 'STOP', 'GO', 'YES', 'NO', 'OKAY', 'FINE', 'GOOD',
            'BAD', 'UP', 'DOWN', 'LEFT', 'RIGHT', 'FIRE', 'WATER', 'EARTH',
            'AIR', 'SUN', 'MOON', 'STAR', 'SKY', 'SEA', 'LAND', 'TREE', 'BIRD',
            'FISH', 'DOG', 'CAT', 'HORSE', 'COW', 'SHEEP', 'BOOK', 'PEN', 'MAP',
            'KEY', 'DOOR', 'WIND', 'RAIN', 'SNOW', 'HOT', 'COLD', 'WARM', 'COOL'
        ],
        medium: [
            'TRAINER', 'SIGNAL', 'MESSAGE', 'RADIO', 'TELEGRAPH', 'EMERGENCY',
            'RESCUE', 'DANGER', 'WARNING', 'NORTH', 'SOUTH', 'EAST', 'WEST',
            'FLOWER', 'BEAUTY', 'STRONG', 'WEAK', 'QUICK', 'SLOW', 'BIG', 'SMALL',
            'HAPPY', 'SAD', 'ANGRY', 'CALM', 'LOUD', 'QUIET', 'BRIGHT', 'DARK',
            'LIGHT', 'HEAVY', 'FAST', 'SLOW', 'NEW', 'OLD', 'YOUNG', 'RICH',
            'POOR', 'HIGH', 'LOW', 'NEAR', 'FAR', 'OPEN', 'CLOSE', 'START',
            'FINISH', 'BEGIN', 'END', 'FIRST', 'LAST', 'BEST', 'WORST',
            'TRAINER', 'SIGNAL', 'MESSAGE', 'RADIO', 'TELEGRAPH', 'EMERGENCY',
            'RESCUE', 'DANGER', 'WARNING', 'NORTH', 'SOUTH', 'EAST', 'WEST',
            'FLOWER', 'BEAUTY', 'STRONG', 'WEAK', 'QUICK', 'SLOW', 'BIG', 'SMALL',
            'HAPPY', 'SAD', 'ANGRY', 'CALM', 'LOUD', 'QUIET', 'BRIGHT', 'DARK',
            'LIGHT', 'HEAVY', 'FAST', 'SLOW', 'NEW', 'OLD', 'YOUNG', 'RICH',
            'POOR', 'HIGH', 'LOW', 'NEAR', 'FAR', 'OPEN', 'CLOSE', 'START',
            'FINISH', 'BEGIN', 'END', 'FIRST', 'LAST', 'BEST', 'WORST'
        ],
        hard: [
            'COMMUNICATION', 'EMERGENCY', 'SITUATION', 'DEPARTMENT', 'ACCOMMODATIONS',
            'CONSTRUCTION', 'IMMEDIATELY', 'ASSISTANCE', 'REQUIRED', 'BUILDING',
            'HOSPITAL', 'RESTAURANT', 'STATION', 'NEARBY', 'AVAILABLE',
            'DIFFICULT', 'IMPORTANT', 'NECESSARY', 'POSSIBLE', 'DIFFERENT',
            'BEAUTIFUL', 'WONDERFUL', 'EXCELLENT', 'FANTASTIC', 'AMAZING',
            'INCREDIBLE', 'WONDERFUL', 'SPECTACULAR', 'MAGNIFICENT', 'EXTRAORDINARY',
            'REMARKABLE', 'OUTSTANDING', 'SUPERIOR', 'EXCEPTIONAL', 'PHENOMENAL',
            'TREMENDOUS', 'ENORMOUS', 'GIGANTIC', 'COLOSSAL', 'MASSIVE',
            'IMMENSE', 'VAST', 'HUGE', 'TREMENDOUS', 'FANTASTIC', 'INCREDIBLE',
            'COMMUNICATION', 'EMERGENCY', 'SITUATION', 'DEPARTMENT', 'ACCOMMODATIONS',
            'CONSTRUCTION', 'IMMEDIATELY', 'ASSISTANCE', 'REQUIRED', 'BUILDING',
            'HOSPITAL', 'RESTAURANT', 'STATION', 'NEARBY', 'AVAILABLE',
            'DIFFICULT', 'IMPORTANT', 'NECESSARY', 'POSSIBLE', 'DIFFERENT',
            'BEAUTIFUL', 'WONDERFUL', 'EXCELLENT', 'FANTASTIC', 'AMAZING',
            'INCREDIBLE', 'WONDERFUL', 'SPECTACULAR', 'MAGNIFICENT', 'EXTRAORDINARY',
            'REMARKABLE', 'OUTSTANDING', 'SUPERIOR', 'EXCEPTIONAL', 'PHENOMENAL',
            'TREMENDOUS', 'ENORMOUS', 'GIGANTIC', 'COLOSSAL', 'MASSIVE',
            'IMMENSE', 'VAST', 'HUGE', 'TREMENDOUS', 'FANTASTIC', 'INCREDIBLE',
            'IOLO IS WATCHING'
        ]
    },
    
    // Sentences organized by difficulty level
    sentencesByLevel: {
        easy: [
            'HELLO WORLD',
            'GOOD MORNING',
            'GOOD NIGHT',
            'THANK YOU',
            'PLEASE HELP',
            'SAVE THE DAY',
            'CALL FOR HELP',
            'STOP NOW',
            'GO AHEAD',
            'YES PLEASE',
            'NO THANKS',
            'OKAY FINE',
            'UP THERE',
            'DOWN HERE',
            'LEFT SIDE',
            'RIGHT NOW',
            'FIRE ALARM',
            'WATER NEEDED',
            'SUN IS HOT',
            'MOON IS BRIGHT',
            'STAR LIGHT',
            'SKY IS BLUE',
            'SEA IS DEEP',
            'LAND IS GREEN',
            'TREE IS TALL',
            'BIRD CAN FLY',
            'FISH CAN SWIM',
            'DOG IS LOYAL',
            'CAT IS CLEAN',
            'HORSE IS FAST',
            'HELLO WORLD',
            'GOOD MORNING',
            'GOOD NIGHT',
            'THANK YOU',
            'PLEASE HELP',
            'SAVE THE DAY',
            'CALL FOR HELP',
            'STOP NOW',
            'GO AHEAD',
            'YES PLEASE',
            'NO THANKS',
            'OKAY FINE',
            'UP THERE',
            'DOWN HERE',
            'LEFT SIDE',
            'RIGHT NOW',
            'FIRE ALARM',
            'WATER NEEDED',
            'SUN IS HOT',
            'MOON IS BRIGHT',
            'STAR LIGHT',
            'SKY IS BLUE',
            'SEA IS DEEP',
            'LAND IS GREEN',
            'TREE IS TALL',
            'BIRD CAN FLY',
            'FISH CAN SWIM',
            'DOG IS LOYAL',
            'CAT IS CLEAN',
            'HORSE IS FAST'
        ],
        medium: [
            'MORSE CODE TRAINER',
            'SOS EMERGENCY CALL',
            'HELP NEEDED NOW',
            'SAVE THE DAY',
            'YOU ARE WELCOME',
            'PLEASE HELP ME',
            'I NEED ASSISTANCE',
            'EMERGENCY SITUATION',
            'FIRE IN BUILDING',
            'MEDICAL EMERGENCY',
            'POLICE NEEDED NOW',
            'AMBULANCE REQUIRED',
            'FIRE DEPARTMENT CALL',
            'RESCUE TEAM NEEDED',
            'DANGER AHEAD STOP',
            'STOP IMMEDIATELY',
            'PROCEED WITH CAUTION',
            'ROAD CLOSED AHEAD',
            'CONSTRUCTION ZONE',
            'SCHOOL ZONE SLOW',
            'HOSPITAL AHEAD',
            'GAS STATION NEARBY',
            'RESTAURANT OPEN NOW',
            'HOTEL ACCOMMODATIONS',
            'PARKING AVAILABLE',
            'NO PARKING ZONE',
            'KEEP OUT AREA',
            'PRIVATE PROPERTY',
            'ENTRANCE ONLY',
            'EXIT THIS WAY',
            'MORSE CODE TRAINER',
            'SOS EMERGENCY CALL',
            'HELP NEEDED NOW',
            'SAVE THE DAY',
            'YOU ARE WELCOME',
            'PLEASE HELP ME',
            'I NEED ASSISTANCE',
            'EMERGENCY SITUATION',
            'FIRE IN BUILDING',
            'MEDICAL EMERGENCY',
            'POLICE NEEDED NOW',
            'AMBULANCE REQUIRED',
            'FIRE DEPARTMENT CALL',
            'RESCUE TEAM NEEDED',
            'DANGER AHEAD STOP',
            'STOP IMMEDIATELY',
            'PROCEED WITH CAUTION',
            'ROAD CLOSED AHEAD',
            'CONSTRUCTION ZONE',
            'SCHOOL ZONE SLOW',
            'HOSPITAL AHEAD',
            'GAS STATION NEARBY',
            'RESTAURANT OPEN NOW',
            'HOTEL ACCOMMODATIONS',
            'PARKING AVAILABLE',
            'NO PARKING ZONE',
            'KEEP OUT AREA',
            'PRIVATE PROPERTY',
            'ENTRANCE ONLY',
            'EXIT THIS WAY'
        ],
        hard: [
            'EMERGENCY MEDICAL ASSISTANCE REQUIRED IMMEDIATELY',
            'FIRE DEPARTMENT RESPONSE NEEDED URGENTLY',
            'POLICE OFFICER BACKUP REQUESTED IMMEDIATELY',
            'AMBULANCE DISPATCH REQUIRED FOR MEDICAL EMERGENCY',
            'RESCUE TEAM DEPLOYMENT NECESSARY FOR CRITICAL SITUATION',
            'CONSTRUCTION ZONE AHEAD PROCEED WITH EXTREME CAUTION',
            'HOSPITAL EMERGENCY ROOM ACCESS AVAILABLE IMMEDIATELY',
            'RESTAURANT ACCOMMODATIONS AVAILABLE FOR LARGE GROUPS',
            'HOTEL RESERVATION CONFIRMATION REQUIRED IMMEDIATELY',
            'PARKING FACILITIES ACCESS RESTRICTED TO AUTHORIZED PERSONNEL',
            'PRIVATE PROPERTY ENTRANCE FORBIDDEN WITHOUT PERMISSION',
            'SCHOOL ZONE SPEED LIMIT ENFORCED DURING OPERATING HOURS',
            'GAS STATION FACILITIES AVAILABLE FOR PUBLIC USE',
            'EMERGENCY EXIT ROUTE CLEARANCE REQUIRED IMMEDIATELY',
            'SECURITY ALARM SYSTEM ACTIVATION IN PROGRESS',
            'WEATHER WARNING SYSTEM ALERT FOR SEVERE CONDITIONS',
            'TRAFFIC CONTROL SYSTEM MALFUNCTION DETECTED',
            'ELECTRICAL POWER SYSTEM RESTORATION IN PROGRESS',
            'WATER SUPPLY SYSTEM MAINTENANCE SCHEDULED',
            'COMMUNICATION NETWORK ACCESS RESTRICTED TEMPORARILY',
            'EMERGENCY MEDICAL ASSISTANCE REQUIRED IMMEDIATELY',
            'FIRE DEPARTMENT RESPONSE NEEDED URGENTLY',
            'POLICE OFFICER BACKUP REQUESTED IMMEDIATELY',
            'AMBULANCE DISPATCH REQUIRED FOR MEDICAL EMERGENCY',
            'RESCUE TEAM DEPLOYMENT NECESSARY FOR CRITICAL SITUATION',
            'CONSTRUCTION ZONE AHEAD PROCEED WITH EXTREME CAUTION',
            'HOSPITAL EMERGENCY ROOM ACCESS AVAILABLE IMMEDIATELY',
            'RESTAURANT ACCOMMODATIONS AVAILABLE FOR LARGE GROUPS',
            'HOTEL RESERVATION CONFIRMATION REQUIRED IMMEDIATELY',
            'PARKING FACILITIES ACCESS RESTRICTED TO AUTHORIZED PERSONNEL',
            'PRIVATE PROPERTY ENTRANCE FORBIDDEN WITHOUT PERMISSION',
            'SCHOOL ZONE SPEED LIMIT ENFORCED DURING OPERATING HOURS',
            'GAS STATION FACILITIES AVAILABLE FOR PUBLIC USE',
            'EMERGENCY EXIT ROUTE CLEARANCE REQUIRED IMMEDIATELY',
            'SECURITY ALARM SYSTEM ACTIVATION IN PROGRESS',
            'WEATHER WARNING SYSTEM ALERT FOR SEVERE CONDITIONS',
            'TRAFFIC CONTROL SYSTEM MALFUNCTION DETECTED',
            'ELECTRICAL POWER SYSTEM RESTORATION IN PROGRESS',
            'WATER SUPPLY SYSTEM MAINTENANCE SCHEDULED',
            'COMMUNICATION NETWORK ACCESS RESTRICTED TEMPORARILY',
            'IOLO IS WATCHING'
        ]
    }
}; 